version: "3"

services:
  frontend:
    image: nginx
    volumes:
      - ./tools/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/home/vino/data/static
      - media_volume:/home/vino/data/files
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build: .
    volumes:
      - static_volume:/home/vino/data/static
      - media_volume:/home/vino/data/files
    ports:
      - "8000:8000"

volumes:
  static_volume:
  media_volume:
