# Generated by Django 2.2.7 on 2019-11-21 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('parameters', models.CharField(blank=True, default='', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViabilityProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('publication', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('dynamics', models.CharField(blank=True, max_length=200)),
                ('constraints', models.CharField(blank=True, max_length=200)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('controls', models.CharField(blank=True, max_length=200)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SV', 'State variable'), ('CV', 'Control variable'), ('DP', 'Dynamics parameter'), ('SP', 'State constraint parameter'), ('TP', 'Target parameter')], max_length=2)),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('longname', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('vp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharekernel.ViabilityProblem', verbose_name='Viability problem')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('publication', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('version', models.CharField(blank=True, default='', max_length=30)),
                ('parameters', models.CharField(blank=True, default='', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('dynamics', models.CharField(blank=True, max_length=200)),
                ('constraints', models.CharField(blank=True, max_length=200)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharekernel.ViabilityProblem', verbose_name='Viability problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('publication', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('file', models.FileField(upload_to='kernels/%Y/%m/%d')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharekernel.DataFormat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharekernel.ParameterSet')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharekernel.Software')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='viabilityproblem',
            constraint=models.UniqueConstraint(fields=('dynamics', 'constraints', 'domain', 'controls', 'target'), name='viabilityproblem_unique'),
        ),
        migrations.AddConstraint(
            model_name='symbol',
            constraint=models.UniqueConstraint(fields=('vp', 'type', 'name'), name='variable_unique'),
        ),
    ]
