# Generated by Django 2.2.7 on 2019-11-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0003_auto_20191125_1245'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='symbol',
            name='variable_unique',
        ),
        migrations.AddConstraint(
            model_name='symbol',
            constraint=models.UniqueConstraint(fields=('vp', 'name'), name='variable_unique'),
        ),
    ]
