# Generated by Django 2.2.8 on 2019-12-02 15:31

from django.db import migrations
import vino.sharekernel.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0005_auto_20191202_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viabilityproblem',
            name='target',
            field=vino.sharekernel.models.InequationsField(blank=True, max_length=200),
        ),
    ]
