# Generated by Django 2.2.8 on 2019-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0006_auto_20191202_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernel',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='software',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='viabilityproblem',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
