# Generated by Django 2.2.9 on 2020-02-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0007_auto_20191215_1935'),
    ]

    operations = [
        migrations.RenameField('Kernel', 'file', 'datafile'),
    ]
