# Generated by Django 2.2.9 on 2020-02-24 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0008_auto_20200213_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kernel',
            name='datafile',
            field=models.FileField(upload_to='kernels/%Y/%m/%d', verbose_name='Data file'),
        ),
        migrations.AlterField(
            model_name='kernel',
            name='params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharekernel.ParameterSet', verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='vp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='sharekernel.ViabilityProblem', verbose_name='Viability problem'),
        ),
    ]
