# Generated by Django 2.2.10 on 2020-02-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0009_auto_20200224_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataformat',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dataformat',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dataformat',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dataformat',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='dataformat',
            name='publication',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dataformat',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataformat',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kernel',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharekernel.DataFormat', verbose_name='Data format'),
        ),
    ]
