# Generated by Django 2.2.11 on 2020-03-09 15:25

from django.db import migrations, models

from vino.core.data import parse_datafile


def update_kernel_size(apps, schema_editor):
    Kernel = apps.get_model('sharekernel', 'Kernel')
    for kernel in Kernel.objects.all():
        kernel.size = parse_datafile(kernel.datafile.path)
        kernel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0010_auto_20200225_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernel',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(
            update_kernel_size,
            reverse_code=migrations.RunPython.noop
        ),
    ]
