# Generated by Django 2.2.11 on 2020-03-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0012_sourcefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernel',
            name='sourcefiles',
            field=models.ManyToManyField(to='sharekernel.SourceFile', verbose_name='Source files'),
        ),
    ]
