# Generated by Django 2.2.12 on 2020-05-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0013_kernel_sourcefiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarGridKernel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sharekernel.kernel',),
        ),
        migrations.CreateModel(
            name='KdTreeKernel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sharekernel.kernel',),
        ),
    ]
