# Generated by Django 2.2.18 on 2021-02-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0014_bargridkernel_kdtreekernel'),
    ]

    operations = [
        # Change verbose_name
        migrations.AlterField(
            model_name='kernel',
            name='params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kernels', to='sharekernel.ParameterSet', verbose_name='Parameters'),
        ),
        # Change related_name
        migrations.AlterField(
            model_name='parameterset',
            name='vp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametersets', to='sharekernel.ViabilityProblem', verbose_name='Viability problem'),
        ),
    ]
