# Generated by Django 2.2.28 on 2022-05-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0015_auto_20210206_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonKernel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sharekernel.kernel',),
        ),
    ]
