# Generated by Django 2.2.28 on 2022-06-06 13:52

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0016_polygonkernel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='file',
            field=models.FilePathField(path=settings.MEDIA_ROOT, verbose_name='Source file'),
        ),
    ]
