# Generated by Django 2.2.28 on 2022-06-06 13:52

from pathlib import Path

from django.db import migrations
from django.conf import settings


def update_sourcefile_file(apps, schema_editor):
    # Make sourcefiles path relative
    SourceFile = apps.get_model('sharekernel', 'SourceFile')
    for sf in SourceFile.objects.all():
        if sf.file.startswith(settings.MEDIA_ROOT):
            sf.file = Path(sf.file).relative_to(settings.MEDIA_ROOT)
            sf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sharekernel', '0017_auto_20220606_1552'),
    ]

    operations = [
        migrations.RunPython(
            update_sourcefile_file,
            reverse_code=migrations.RunPython.noop
        ),
    ]
